const body=document.body,header=document.getElementById('siteHeader');
const motion=document.createElement('link');motion.rel='stylesheet';motion.href='motion.css';document.head.appendChild(motion);
body.insertAdjacentHTML('afterbegin','<div class="page-loader" id="pageLoader"><div class="loader-brand"><span class="loader-mark"></span><strong>CONS</strong><small>BUILDING WHAT COMES NEXT</small></div><div class="loader-line"><i></i></div></div><div class="scroll-progress" id="scrollProgress"></div><div class="cursor-dot" id="cursorDot"></div><div class="cursor-ring" id="cursorRing"></div>');
const hero=document.querySelector('.hero');hero.classList.add('video-hero');
hero.innerHTML=`<div class="hero-slider" id="heroSlider">
${[
['Integrated Construction Partner','We build what progress demands.','CONS delivers landmark buildings, infrastructure and complex EPC projects through one disciplined delivery platform.','Premium mixed-use delivery','From design coordination to handover, we align engineering, procurement and site control into one accountable path.','https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4','https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=2400&q=88'],
['Engineering + Procurement + Construction','One team. One standard. One outcome.','We connect technical intelligence, disciplined procurement and field execution under a single operating model built for certainty.','Infrastructure with execution depth','Roads, public-realm works, utilities and enabling packages are coordinated through measurable planning and field discipline.','https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4','https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=2400&q=88'],
["Built for Saudi Arabia's Next Chapter",'Local insight. Global delivery discipline.','A modern Saudi contractor focused on premium execution, safety leadership, localization and measurable value creation.','Executive-grade project governance','We translate board-level ambition into site-level clarity with reporting, sequencing, quality assurance and delivery controls.','https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4','https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=2400&q=88'],
['High-performance field delivery','Crafted to feel global. Built to deliver locally.','Every touchpoint is designed to reflect premium capability—from the first client meeting to the final handover milestone.','Luxury finishes and public realm','Specialized packages, finishing quality and public-realm detailing are delivered with the same rigor as core construction works.','https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4','https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=2400&q=88']
].map((x,i)=>`<article class="hero-slide ${i?'':'active'}"><video class="hero-video" autoplay muted loop playsinline poster="${x[6]}"><source src="${x[5]}" type="video/mp4"></video><span class="hero-shade"></span><div class="hero-grid"><div class="hero-content"><p class="eyebrow">${x[0]}</p><h1>${x[1]}</h1><p class="hero-copy">${x[2]}</p></div><aside class="hero-aside"><p class="hero-mini-label">Featured capability</p><h3>${x[3]}</h3><p>${x[4]}</p><div class="hero-aside-metrics"><div><strong>${i+1<10?'0':''}${i+1}</strong><span>Premium sector experience</span></div><div><strong>${['25+','360°','HSE','VIP'][i]}</strong><span>Measured delivery discipline</span></div></div></aside></div></article>`).join('')}
</div><div class="hero-strip">${['Buildings','Infrastructure','EPC & Industrial','Public Realm'].map((x,i)=>`<button class="hero-key ${i?'':'active'}" data-slide="${i}"><small>Sector 0${i+1}</small><strong>${x}</strong></button>`).join('')}</div><div class="hero-bottom"><div class="hero-controls"><button id="prevSlide">←</button><span id="slideCount">01 / 04</span><button id="nextSlide">→</button></div><a class="hero-cta magnetic" href="#about">Discover CONS <span>↘</span></a></div>`;
window.addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>20));
const slides=[...document.querySelectorAll('.hero-slide')],keys=[...document.querySelectorAll('.hero-key')],count=document.getElementById('slideCount');let current=0;
function showSlide(i){slides[current].classList.remove('active');current=(i+slides.length)%slides.length;slides[current].classList.add('active');keys.forEach((k,n)=>k.classList.toggle('active',n===current));count.textContent=String(current+1).padStart(2,'0')+' / 04';slides.forEach((s,n)=>{const v=s.querySelector('video');n===current?v.play().catch(()=>{}):v.pause()})}
document.getElementById('nextSlide').onclick=()=>showSlide(current+1);document.getElementById('prevSlide').onclick=()=>showSlide(current-1);keys.forEach((k,i)=>k.onclick=()=>showSlide(i));setInterval(()=>showSlide(current+1),7000);showSlide(0);
const menu=document.getElementById('mobileMenu');document.getElementById('menuBtn').onclick=()=>{menu.classList.add('open');menu.setAttribute('aria-hidden','false')};document.getElementById('mobileClose').onclick=()=>{menu.classList.remove('open');menu.setAttribute('aria-hidden','true')};menu.querySelectorAll('a').forEach(a=>a.onclick=()=>menu.classList.remove('open'));
document.querySelectorAll('.service-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.service-tab').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.service-panel').forEach(p=>p.classList.remove('active'));btn.classList.add('active');document.getElementById(btn.dataset.target).classList.add('active')}));
let arabic=false;document.getElementById('langBtn').onclick=()=>{arabic=!arabic;body.classList.toggle('rtl',arabic);document.documentElement.lang=arabic?'ar':'en';document.documentElement.dir=arabic?'rtl':'ltr';document.getElementById('langBtn').textContent=arabic?'EN':'AR'};
document.querySelectorAll('main section,.footer').forEach(x=>x.classList.add('reveal-section'));const ro=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');ro.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal-section').forEach(x=>ro.observe(x));
const loader=document.getElementById('pageLoader');window.addEventListener('load',()=>setTimeout(()=>loader.classList.add('done'),350));setTimeout(()=>loader.classList.add('done'),2200);
const progress=document.getElementById('scrollProgress');addEventListener('scroll',()=>{const m=document.documentElement.scrollHeight-innerHeight;progress.style.width=(m?scrollY/m*100:0)+'%'},{passive:true});
const dot=document.getElementById('cursorDot'),ring=document.getElementById('cursorRing');let mx=0,my=0,rx=0,ry=0;addEventListener('mousemove',e=>{mx=e.clientX;my=e.clientY;dot.style.cssText+=`;opacity:1;left:${mx}px;top:${my}px`;ring.style.opacity=1});(function loop(){rx+=(mx-rx)*.16;ry+=(my-ry)*.16;ring.style.left=rx+'px';ring.style.top=ry+'px';requestAnimationFrame(loop)})();document.querySelectorAll('a,button,.project-card').forEach(x=>{x.onmouseenter=()=>ring.classList.add('hover');x.onmouseleave=()=>ring.classList.remove('hover')});
document.querySelectorAll('.project-card').forEach(c=>{c.classList.add('tilt-card');c.onmousemove=e=>{const r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;c.style.transform=`perspective(900px) rotateX(${y*-7}deg) rotateY(${x*9}deg) scale(1.015)`};c.onmouseleave=()=>c.style.transform=''});